### ISSUE TITLE
I seem to be getting a lot of these on my machines.

### ISSUE THREAD

**Issue by Just-another-pleb** [bartbutenaers/node-red-contrib-vcgencmd#5]
It seems about 2 weeks apart, but then it all just falls over.

First the error:

```
{"message":"Error: spawn EIO","source":{"id":"286d9c48.9ce52c","type":"ping","name":"TV","count":1},"stack":"Error: spawn EIO\n    at ChildProcess.spawn (internal/child_process.js:313:11)\n    at exports.spawn (child_process.js:508:9)\n    at doPing (/home/pi/.node-red/node_modules/node-red-node-ping/88-ping.js:40:14)\n    at PingNode._inputCallback (/home/pi/.node-red/node_modules/node-red-node-ping/88-ping.js:120:36)\n    at hooks.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:203:26)\n    at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/hooks.js:113:9)\n    at PingNode.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:195:11)\n    at PingNode.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:179:25)\n    at PingNode.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:476:10)\n    at Immediate.<anonymous> (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:657:52)"}
```

System:
RasPi 3B
Stretch
NR 1.2.6
Dashboard - if this is of any help  2.26.1
vcgencmd 1.0.3

**Comment by bartbutenaers** [comment]
Hi @Just-another-pleb,
It is not clear to me how this error is related to the vcgencmd node?
In your error I see that it is related to the Ping node (88-ping.js), which is part of the [node-red-nodes](https://github.com/node-red/node-red-nodes) repository.
Unless I misunderstood your problem, you should open an issue in that repository and close this one.
Bart

**Comment by Just-another-pleb** [comment]
Argh, sorry.  I was flooded with a lot of errors and pasted the wrong one.

I'll see if I can find the one I meant.

Sorry.

(Isn't it typical)
As soon as I am waiting for an error to happen, it doesn't happen.

I am going away in a couple of weeks and (typically - again) it will happen when I am away.
